# Generated by Django 5.2.3 on 2026-04-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorOfferCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('discountType', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('discountAmount', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('couponFor', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('eventSpecialWord', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
