# Generated by Django 5.2.3 on 2026-04-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_eventproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslideshares',
            name='projectId',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.eventproject'),
        ),
        migrations.AddField(
            model_name='eventslidesharesattandees',
            name='projectId',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.eventproject'),
        ),
        migrations.AddField(
            model_name='slidesharesaccesspersons',
            name='projectId',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.eventproject'),
        ),
    ]
