# Generated by Django 5.2.3 on 2026-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_eventslideshares_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='contactHubspotId',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='eventCityShortCode',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='eventColorName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='eventPostponed',
            field=models.CharField(blank=True, default='false', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='eventShortDate',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='eventShortLocation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='favicon',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='googleTranslate',
            field=models.CharField(blank=True, default='false', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='hubspotDisposition',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='hubspotEmailStatus',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='hubspotId',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='industryName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='previousAgenda',
            field=models.CharField(blank=True, default='false', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='recaptchaKey',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='stripeMode',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventgeneralsettings',
            name='currencyPosition',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
