# Generated by Django 5.2.3 on 2026-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_eventdetails_contacthubspotid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageSeoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pageMetaTitle', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pageMetaDescription', models.TextField(blank=True, null=True)),
                ('pageOgImage', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
