# Generated by Django 5.2.3 on 2026-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='footerOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerOptionsName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('footerOptionsPath', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('isChecked', models.CharField(default='No', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='No', max_length=50)),
                ('updated_by', models.CharField(default='No', max_length=50)),
                ('isDelete', models.CharField(default='No', max_length=10)),
            ],
        ),
    ]
