# Generated by Django 5.2.3 on 2026-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0004_agendasubscriber_calendersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='themecolorsettings',
            name='editorStyle',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='themecolorsettings',
            name='headerContent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='themecolorsettings',
            name='headerType',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
