# Generated by Django 5.2.3 on 2026-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0005_themecolorsettings_editorstyle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmodule',
            name='id_attr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
