# Generated by Django 5.2.3 on 2026-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myadmin', '0006_sidebarmodule_id_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebarmodule',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
