from django.contrib import admin
from .models import eventDetails,eventSpeakers,eventTestimonials,eventExpertSpeakers,eventPastAttandees,eventSponsors,eventIndustryTrends,relatedEvents,eventDeligatePackages,deligatePackageInclusionPoints,eventAgenda,eventCoreAttandees,eventParticipatedIndustries,eventFaqs,registeredCompanyDetails,registeredDelegates,delegatesAddOns,paymentOptionImage,offerCoupon,delegateTransectionData,eventGeneralSettings,offerCouponHistory,addOnsHistory,sponsorPackageTypes,sponsorPackageAddOnTypes,sponsorPackageAddOns,sponseredCompanyDetails,registeredSponseredDelegates,sponsoredCompanyAddOnsDetails,sponsorCompanyTransectionData,groupPassRegistrationRequestData,sponsorOfferCouponHistory,eventLeaders,eventSlideShares,eventSlideSharesAttandees,slideSharesAccessPersons, payOnlineTransectionData,blockedEmailDomains,sponsorOfferCoupon,eventProject,pageSeoSettings
# Register your models here.
admin.site.register(eventDetails)
admin.site.register(eventSpeakers)
admin.site.register(eventTestimonials)
admin.site.register(eventExpertSpeakers)
admin.site.register(eventPastAttandees)
admin.site.register(eventSponsors)
admin.site.register(eventIndustryTrends)
admin.site.register(relatedEvents)
admin.site.register(eventDeligatePackages)
admin.site.register(deligatePackageInclusionPoints)
admin.site.register(eventAgenda)
admin.site.register(eventParticipatedIndustries)
admin.site.register(eventCoreAttandees)
admin.site.register(eventFaqs)
admin.site.register(registeredCompanyDetails)
admin.site.register(registeredDelegates)
admin.site.register(delegatesAddOns)
admin.site.register(paymentOptionImage)
admin.site.register(offerCoupon)
admin.site.register(delegateTransectionData)
admin.site.register(eventGeneralSettings)
admin.site.register(offerCouponHistory)
admin.site.register(addOnsHistory)
# admin.site.register(sponsorBenefits)
admin.site.register(sponsorPackageTypes)
# admin.site.register(sponsorPackageInclusions)
admin.site.register(sponsorPackageAddOnTypes)
admin.site.register(sponsorPackageAddOns)
admin.site.register(sponseredCompanyDetails)
admin.site.register(registeredSponseredDelegates)
admin.site.register(sponsoredCompanyAddOnsDetails)
admin.site.register(sponsorCompanyTransectionData)
admin.site.register(groupPassRegistrationRequestData)
admin.site.register(sponsorOfferCouponHistory)
admin.site.register(eventLeaders)
admin.site.register(eventSlideShares)
admin.site.register(eventSlideSharesAttandees)
admin.site.register(slideSharesAccessPersons)
admin.site.register(payOnlineTransectionData)
admin.site.register(blockedEmailDomains)
admin.site.register(sponsorOfferCoupon)
admin.site.register(eventProject)
admin.site.register(pageSeoSettings)