from django.db import models
from tkinter import CASCADE
from django.db.models.deletion import CASCADE

class eventDetails(models.Model):
    eventName = models.CharField(default="",max_length=100,null=True, blank=True)
    eventShortCode = models.CharField(default="",max_length=100,null=True, blank=True)
    eventDate = models.CharField(default="",max_length=100,null=True, blank=True)
    eventLocation = models.CharField(default="",max_length=100,null=True, blank=True)
    eventYear = models.CharField(default="",max_length=100,null=True, blank=True)
    eventShortDate = models.CharField(default="",max_length=100,null=True, blank=True)
    eventShortLocation = models.CharField(default="",max_length=100,null=True, blank=True)
    eventColorName = models.CharField(default="",max_length=100,null=True, blank=True)
    eventCityShortCode = models.CharField(default="",max_length=100,null=True, blank=True)
    eventPostponed = models.CharField(default="false",max_length=100,null=True, blank=True)
    industryName = models.CharField(default="",max_length=100,null=True, blank=True)
    previousAgenda = models.CharField(default="false",max_length=100,null=True, blank=True)
    hubspotDisposition = models.CharField(default="",max_length=100,null=True, blank=True)
    hubspotEmailStatus = models.CharField(default="",max_length=100,null=True, blank=True)
    eventType = models.CharField(default="",max_length=100,null=True, blank=True)
    isSeoEnable = models.CharField(default="",max_length=100,null=True, blank=True)
    agendaVersion = models.CharField(default="",max_length=100,null=True, blank=True)
    stripeMode = models.CharField(default="",max_length=100,null=True, blank=True)
    recaptchaKey = models.CharField(default="",max_length=150,null=True, blank=True)
    hubspotId = models.CharField(default="",max_length=150,null=True, blank=True)
    contactHubspotId = models.CharField(default="",max_length=150,null=True, blank=True)
    googleTranslate = models.CharField(default="false",max_length=150,null=True, blank=True)
    favicon = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventSpeakers(models.Model):
    eventSpeakerName = models.CharField(default="",max_length=100,null=True, blank=True)
    eventSpeakerCompany = models.CharField(default="",max_length=100,null=True, blank=True)
    eventSpeakerShortDescription = models.TextField(null=True,blank=True)
    eventSpeakerDescription = models.TextField(null=True,blank=True)
    viewSpeakerButtonLabel = models.CharField(default="",max_length=100,null=True, blank=True)
    speakerProfilePageLink = models.CharField(default="",max_length=150,null=True, blank=True)
    eventSpeakerHomePageImage = models.TextField(null=True,blank=True)
    eventSpeakerProfilePageImage = models.TextField(null=True,blank=True)
    eventSpeakerFeaturedPageImage = models.TextField(null=True,blank=True)
    eventSpeakerEmail = models.CharField(default="",max_length=100,null=True, blank=True)
    eventSpeakerProposedTitle = models.CharField(default="",max_length=100,null=True, blank=True)
    isParticipated = models.CharField(default="No",max_length=10)
    eventSpeakerProfilePageDescription = models.TextField(null=True,blank=True)
    eventSpeakerMetaTitle = models.CharField(null=True,blank=True)
    eventSpeakerMetaDescription = models.TextField(null=True,blank=True)
    eventSpeakerLinkedinFollowers = models.IntegerField(default=0, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventTestimonials(models.Model):
    personName = models.CharField(default="",max_length=100,null=True, blank=True)
    personCompany = models.CharField(default="",max_length=100,null=True, blank=True)
    personMessage = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventExpertSpeakers(models.Model):
    expertSpeakerName = models.CharField(default="",max_length=100,null=True, blank=True)
    expertSpeakerCompany = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventPastAttandees(models.Model):
    pastAttandeeName = models.CharField(default="",max_length=100,null=True, blank=True)
    pastAttandeeLogo = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventSponsors(models.Model):
    sponsorComapnyName = models.CharField(default="",max_length=100,null=True, blank=True)
    sponsorComapnyLogo = models.CharField(default="",max_length=100,null=True, blank=True)
    sponsorType = models.CharField(default="",max_length=100,null=True, blank=True)
    sponsorComapnyBioDescription = models.TextField(null=True,blank=True)
    sponsorWebsite = models.CharField(default="",max_length=100,null=True, blank=True)
    sponsorComapnyBioLogo = models.CharField(default="",max_length=100,null=True, blank=True)
    sponsorEmail = models.CharField(default="",max_length=100,null=True, blank=True)
    sponsorMobile = models.CharField(default="",max_length=100,null=True, blank=True)
    relateComapnyPersonName = models.CharField(default="",max_length=100,null=True, blank=True)
    eventSponsorMetaTitle = models.CharField(null=True,blank=True)
    eventSponsorMetaDescription = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventIndustryTrends(models.Model):
    trendTitle = models.CharField(default="",max_length=100,null=True, blank=True)
    trendRedirectPath = models.CharField(default="",max_length=100,null=True, blank=True)
    trendShortDescription = models.TextField(null=True,blank=True)
    trendLongDescription = models.TextField(null=True,blank=True)
    trendMetaTitle = models.CharField(null=True,blank=True)
    trendMetaDescription = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class relatedEvents(models.Model):
    eventName = models.CharField(default="",max_length=150,null=True, blank=True)
    eventLocation = models.CharField(default="",max_length=150,null=True, blank=True)
    eventWebsiteLink = models.CharField(default="",max_length=150,null=True, blank=True)
    eventDate = models.CharField(default="",max_length=150,null=True, blank=True)
    eventImage = models.CharField(default="",max_length=150,null=True, blank=True)
    eventHoverImage = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventDeligatePackages(models.Model):
    deligatePackageName = models.CharField(default="",max_length=150,null=True, blank=True)
    deligatePackagePrice = models.CharField(default="",max_length=150,null=True, blank=True)
    deligatePackageStatus = models.CharField(default="",max_length=150,null=True, blank=True)
    deligatePackageShowOrder = models.CharField(default="",max_length=150,null=True, blank=True)
    deligatePackageExpiryDate = models.DateField(null=True,max_length=100,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class deligatePackageInclusionPoints(models.Model):
    inclusionPointIcon = models.CharField(default="",max_length=150,null=True, blank=True)
    inclusionPointDescription = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

# class eventAgenda(models.Model):
#     status = models.CharField(default="",max_length=150,null=True, blank=True)
#     heading = models.CharField(default="",max_length=200,null=True, blank=True)
#     day = models.CharField(default="",max_length=200,null=True, blank=True)
#     startTime = models.CharField(default="",max_length=150,null=True, blank=True)
#     endTime = models.CharField(default="",max_length=150,null=True, blank=True)
#     sponsorBy = models.CharField(default="",max_length=150,null=True, blank=True)
#     sortOrder = models.IntegerField(default=0, null=True, blank=True)
#     speakerFormat = models.CharField(default="",max_length=150,null=True, blank=True)
#     bulletPoints = models.TextField(null=True,blank=True)
#     industryTrends = models.TextField(null=True,blank=True)

#     speaker1Bullets = models.TextField(null=True,blank=True)
#     speaker2Bullets = models.TextField(null=True,blank=True)

#     panelSpeakerImages = models.TextField(null=True,blank=True)
#     panelSpeakerIds = models.TextField(null=True,blank=True)
#     panelModerators = models.TextField(null=True,blank=True)
#     selectedSpeakers = models.TextField(null=True,blank=True)

#     singleSpeakerAgendaImg = models.CharField(default="",max_length=150,null=True, blank=True)
#     singleSpeakerCompanyImg = models.CharField(default="",max_length=150,null=True, blank=True)
#     singleSpeakerId = models.CharField(default="",max_length=150,null=True, blank=True)

#     Speaker1AgendaImg = models.CharField(default="",max_length=150,null=True, blank=True)
#     Speaker1CompanyImg = models.CharField(default="",max_length=150,null=True, blank=True)
#     Speaker1Id = models.CharField(default="",max_length=150,null=True, blank=True)

#     Speaker2AgendaImg = models.CharField(default="",max_length=150,null=True, blank=True)
#     Speaker2CompanyImg = models.CharField(default="",max_length=150,null=True, blank=True)
#     Speaker2Id = models.CharField(default="",max_length=150,null=True, blank=True)

#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     created_by = models.CharField(null=False,max_length=50,default='No')
#     updated_by = models.CharField(null=False,max_length=50,default='No')
#     isDelete = models.CharField(default="No",max_length=10)

class eventAgenda(models.Model):
    status = models.CharField(default="", max_length=150, null=True, blank=True)
    heading = models.CharField(default="", max_length=200, null=True, blank=True)
    day = models.CharField(default="", max_length=200, null=True, blank=True)
    startTime = models.CharField(default="", max_length=150, null=True, blank=True)
    endTime = models.CharField(default="", max_length=150, null=True, blank=True)
    sponsorBy = models.CharField(default="", max_length=150, null=True, blank=True)
    sortOrder = models.IntegerField(default=0, null=True, blank=True)
    speakerFormat = models.CharField(default="", max_length=150, null=True, blank=True)
    bulletPoints = models.TextField(null=True, blank=True)
    industryTrends = models.TextField(null=True, blank=True)

    speaker1Bullets = models.TextField(null=True, blank=True)
    speaker2Bullets = models.TextField(null=True, blank=True)

    panelSpeakerImages = models.TextField(null=True, blank=True)
    panelSpeakerIds = models.TextField(null=True, blank=True)
    panelModerators = models.TextField(null=True, blank=True)
    selectedSpeakers = models.TextField(null=True, blank=True)

    # ── Single Speaker ──
    singleSpeakerAgendaImg = models.CharField(default="", max_length=500, null=True, blank=True)
    singleSpeakerCompanyImg = models.CharField(default="", max_length=500, null=True, blank=True)
    singleSpeakerId = models.CharField(default="", max_length=150, null=True, blank=True)
    singleSpeakerName = models.CharField(default="", max_length=200, null=True, blank=True)       # NEW
    singleSpeakerCompanyName = models.CharField(default="", max_length=200, null=True, blank=True) # NEW

    # ── Two Speakers ──
    Speaker1AgendaImg = models.CharField(default="", max_length=500, null=True, blank=True)
    Speaker1CompanyImg = models.CharField(default="", max_length=500, null=True, blank=True)
    Speaker1Id = models.CharField(default="", max_length=150, null=True, blank=True)
    speaker1Name = models.CharField(default="", max_length=200, null=True, blank=True)            # NEW
    speaker1CompanyName = models.CharField(default="", max_length=200, null=True, blank=True)     # NEW
    selectedSpeaker1 = models.TextField(null=True, blank=True)                                    # NEW (JSON)

    Speaker2AgendaImg = models.CharField(default="", max_length=500, null=True, blank=True)
    Speaker2CompanyImg = models.CharField(default="", max_length=500, null=True, blank=True)
    Speaker2Id = models.CharField(default="", max_length=150, null=True, blank=True)
    speaker2Name = models.CharField(default="", max_length=200, null=True, blank=True)            # NEW
    speaker2CompanyName = models.CharField(default="", max_length=200, null=True, blank=True)     # NEW
    selectedSpeaker2 = models.TextField(null=True, blank=True)                                    # NEW (JSON)

    # ── Panel Speaker ──
    panelSpeakers = models.TextField(null=True, blank=True)                                       # NEW (JSON array)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False, max_length=50, default='No')
    updated_by = models.CharField(null=False, max_length=50, default='No')
    isDelete = models.CharField(default="No", max_length=10)
    
class eventCoreAttandees(models.Model):
    corAttandeeName = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventParticipatedIndustries(models.Model):
    industryName = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventFaqs(models.Model):
    faqQuestion = models.CharField(default="",max_length=150,null=True, blank=True)
    faqAnswer = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class registeredCompanyDetails(models.Model):
    companyName = models.CharField(default="",max_length=150,null=True, blank=True)
    companyWebsite = models.CharField(default="",max_length=150,null=True, blank=True)
    companyAddress = models.TextField(null=True,blank=True)
    companyCountry = models.CharField(default="",max_length=150,null=True, blank=True)
    companyState = models.CharField(default="",max_length=150,null=True, blank=True)
    companyCity = models.CharField(default="",max_length=150,null=True, blank=True)
    companyPincode = models.CharField(default="",max_length=150,null=True, blank=True)
    purchasedDelegatePackageId = models.ForeignKey(eventDeligatePackages,default='',on_delete=CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class registeredDelegates(models.Model):
    relatedCompanyId = models.ForeignKey(registeredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    firstName = models.CharField(default="",max_length=150,null=True, blank=True)
    lastName = models.CharField(default="",max_length=150,null=True, blank=True)
    mobile = models.CharField(default="",max_length=150,null=True, blank=True)
    position = models.CharField(default="",max_length=150,null=True, blank=True)
    delegateEmail = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class delegatesAddOns(models.Model):
    addOnPointName = models.CharField(default="",max_length=150,null=True, blank=True)
    additionalPrice = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class paymentOptionImage(models.Model):
    paymentOptionImageLink = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class offerCoupon(models.Model):
    couponCode = models.CharField(default="",max_length=150,null=True, blank=True)
    discountType = models.CharField(default="",max_length=150,null=True, blank=True)
    discountAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    couponFor = models.CharField(default="",max_length=150,null=True, blank=True)
    eventSpecialWord = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class sponsorOfferCoupon(models.Model):
    couponCode = models.CharField(default="",max_length=150,null=True, blank=True)
    discountType = models.CharField(default="",max_length=150,null=True, blank=True)
    discountAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    couponFor = models.CharField(default="",max_length=150,null=True, blank=True)
    eventSpecialWord = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class delegateTransectionData(models.Model):
    relatedCompanyId = models.ForeignKey(registeredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    invoiceNo = models.CharField(default="",max_length=150,null=True, blank=True)
    totalPassAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    discountAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    addOnsAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    taxableCharge = models.CharField(default="",max_length=150,null=True, blank=True)
    totalPaidAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    transectionId = models.CharField(default="",max_length=150,null=True, blank=True)
    transectionType = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventGeneralSettings(models.Model):
    purchaseTaxPercent = models.CharField(default="",max_length=150,null=True, blank=True)
    currencyName = models.CharField(default="",max_length=150,null=True, blank=True)
    currencySymbol = models.CharField(default="",max_length=150,null=True, blank=True)
    currencyPosition = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class offerCouponHistory(models.Model):
    relatedCompanyId = models.ForeignKey(registeredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    offerCouponId = models.ForeignKey(offerCoupon,default='',on_delete=CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class addOnsHistory(models.Model):
    relatedCompanyId = models.ForeignKey(registeredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    addOnId = models.ForeignKey(delegatesAddOns,default='',on_delete=CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

# class sponsorBenefits (models.Model):
#     benefitTitle = models.CharField(default="",max_length=150,null=True, blank=True)
#     benefitInfo = models.CharField(default="",max_length=150,null=True, blank=True)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     created_by = models.CharField(null=False,max_length=50,default='No')
#     updated_by = models.CharField(null=False,max_length=50,default='No')
#     isDelete = models.CharField(default="No",max_length=10)

class sponsorPackageTypes (models.Model):
    sponsorPackageType = models.CharField(default="",max_length=150,null=True, blank=True)
    sponsorPackagePrice = models.CharField(default="",max_length=150,null=True, blank=True)
    sponsorPackageCuttingPrice = models.CharField(default="",max_length=150,null=True, blank=True)
    delegatePassQty = models.CharField(default="",max_length=150,null=True, blank=True)
    inviteDiscount = models.CharField(default="",max_length=150,null=True, blank=True)
    exhibitSpace = models.CharField(default="",max_length=150,null=True, blank=True)
    sponsorPackageShowOrder = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

# class sponsorPackageInclusions (models.Model):
#     sponsorPackageTypeId = models.ForeignKey(sponsorPackageTypes,default='',on_delete=CASCADE,null=True,blank=True)
#     sponsorBenifitId = models.ForeignKey(sponsorBenefits,default='',on_delete=CASCADE,null=True,blank=True)
#     benefitValue = models.CharField(default="",max_length=150,null=True, blank=True)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#     created_by = models.CharField(null=False,max_length=50,default='No')
#     updated_by = models.CharField(null=False,max_length=50,default='No')
#     isDelete = models.CharField(default="No",max_length=10)

class sponsorPackageAddOnTypes(models.Model):
    addOnTypeName = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class sponsorPackageAddOns(models.Model):
    sponsorPackageAddOnTypeId = models.ForeignKey(sponsorPackageAddOnTypes,default='',on_delete=CASCADE,null=True,blank=True)
    sponsorAddOnName = models.CharField(default="",max_length=150,null=True, blank=True)
    sponsorAddOnPrice = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class sponseredCompanyDetails(models.Model):
    sponsorPackageTypeId = models.ForeignKey(sponsorPackageTypes,default='',on_delete=CASCADE,null=True,blank=True)
    companyName = models.CharField(default="",max_length=150,null=True, blank=True)
    companyWebsite = models.CharField(default="",max_length=150,null=True, blank=True)
    companyAddress = models.TextField(null=True,blank=True)
    companyCountry = models.CharField(default="",max_length=150,null=True, blank=True)
    companyState = models.CharField(default="",max_length=150,null=True, blank=True)
    companyCity = models.CharField(default="",max_length=150,null=True, blank=True)
    companyPincode = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class registeredSponseredDelegates(models.Model):
    relatedSponsorCompanyId = models.ForeignKey(sponseredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    firstName = models.CharField(default="",max_length=150,null=True, blank=True)
    lastName = models.CharField(default="",max_length=150,null=True, blank=True)
    mobile = models.CharField(default="",max_length=150,null=True, blank=True)
    position = models.CharField(default="",max_length=150,null=True, blank=True)
    delegateEmail = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class sponsoredCompanyAddOnsDetails(models.Model):
    relatedSponsorCompanyId = models.ForeignKey(sponseredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    relatedSponsorAddOnsId = models.ForeignKey(sponsorPackageAddOns,default='',on_delete=CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class sponsorOfferCouponHistory(models.Model):
    relatedSponsorCompanyId = models.ForeignKey(sponseredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    offerCouponId = models.ForeignKey(offerCoupon,default='',on_delete=CASCADE,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class sponsorCompanyTransectionData(models.Model):
    relatedSponsorCompanyId = models.ForeignKey(sponseredCompanyDetails,default='',on_delete=CASCADE,null=True,blank=True)
    invoiceNo = models.CharField(default="",max_length=150,null=True, blank=True)
    additionalDelegateAmoount = models.CharField(default="",max_length=150,null=True, blank=True)
    totalPassAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    discountAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    addOnsAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    taxableCharge = models.CharField(default="",max_length=150,null=True, blank=True)
    totalPaidAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    transectionId = models.CharField(default="",max_length=150,null=True, blank=True)
    transectionType = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class groupPassRegistrationRequestData(models.Model):
    requesterName = models.CharField(default="",max_length=150,null=True, blank=True)
    requesterCompanyName = models.CharField(default="",max_length=150,null=True, blank=True)
    requesterEmail = models.CharField(default="",max_length=150,null=True, blank=True)
    requesterMobile = models.CharField(default="",max_length=150,null=True, blank=True)
    requesterInterest = models.CharField(default="",max_length=150,null=True, blank=True)
    noOfAttandees = models.CharField(default="",max_length=150,null=True, blank=True)
    requesterMessage = models.TextField(null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventLeaders(models.Model):
    leaderName = models.CharField(default="",max_length=100,null=True, blank=True)
    leaderLogo = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventProject(models.Model):
    projectYear = models.CharField(default="",max_length=100,null=True, blank=True)
    password = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)
class eventSlideShares(models.Model):
    projectId = models.ForeignKey(eventProject,default='',on_delete=CASCADE,null=True,blank=True)
    author = models.CharField(default="",max_length=100,null=True, blank=True)
    authorCompany = models.CharField(default="",max_length=100,null=True, blank=True)
    heading = models.CharField(default="", max_length=200, null=True, blank=True)
    pptImage = models.TextField(null=True,blank=True)
    pptLink = models.TextField(null=True,blank=True)
    projectYear = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class eventSlideSharesAttandees(models.Model):
    projectId = models.ForeignKey(eventProject,default='',on_delete=CASCADE,null=True,blank=True)
    companyName = models.CharField(default="",max_length=100,null=True, blank=True)
    delegateName = models.CharField(default="",max_length=100,null=True, blank=True)
    projectYear = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class slideSharesAccessPersons(models.Model):
    projectId = models.ForeignKey(eventProject,default='',on_delete=CASCADE,null=True,blank=True)
    email = models.CharField(default="",max_length=100,null=True, blank=True)
    eventPassword = models.CharField(default="",max_length=100,null=True, blank=True)
    projectYear = models.CharField(default="",max_length=100,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class payOnlineTransectionData(models.Model):
    invoiceNo = models.CharField(default="",max_length=150,null=True, blank=True)
    totalPayAmount = models.CharField(default="",max_length=150,null=True, blank=True)
    email = models.CharField(default="",max_length=100,null=True, blank=True)
    transectionId = models.CharField(default="",max_length=150,null=True, blank=True)
    transectionType = models.CharField(default="",max_length=150,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)

class blockedEmailDomains(models.Model):
    domainName = models.CharField(default="",max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.CharField(null=False,max_length=50,default='No')
    updated_by = models.CharField(null=False,max_length=50,default='No')
    isDelete = models.CharField(default="No",max_length=10)